syntax on
set number
set relativenumber
set cursorline
set hlsearch
set incsearch
set showcmd
set wildmenu
set ignorecase
set smartcase
set nowrap
set showmatch
set ruler
" tab space config
set tabstop=4
set shiftwidth=4
set autoindent
" save and quite key map
map S :w<CR>
map Q :q<CR>
"key mapping in insert mode
imap jj <ESC>
inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>
set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
"keep 5 line of on buttom and head
set scrolloff=5
"change cursor style of insert mode
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

set mouse=a
set encoding=utf-8
"cursor on last exit
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"vim config change take effect immediately
autocmd BufWritePost $MYVIMRC source $MYVIMRC
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'connorholyday/vim-snazzy'
" File navigation
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }

" Auto pairs
Plug 'jiangmiao/auto-pairs'
call plug#end()


let g:SnazzyTransparent = 1
color snazzy

map <F3> :NERDTreeMirror<CR>
map <F3> :NERDTreeToggle<CR>
