syntax on
set number
set cursorline
set hlsearch
set incsearch
set showcmd
set wildmenu
set ignorecase
set smartcase
set wrap
map S :w<CR>
map Q :q<CR>

set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
"keep 5 line of on buttom and head
set scrolloff=5
"change cursor style of insert mode
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

set mouse=a
set encoding=utf-8
"cursor on last exit
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'connorholyday/vim-snazzy'

" File navigation
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin'

call plug#end()
let g:SnazzyTransparent = 1
color snazzy
map t :NERDTreeToggle<CR>
map tt :NERDTreeClose<CR>

